agencia_actors_frontend:
    resource: "@AgenciaActorsFrontendBundle/Resources/config/routing.yml"
    prefix:   /agencia

agencia_actors_backend:
    resource: "@AgenciaActorsBackendBundle/Resources/config/routing.yml"
    prefix:   /agencia/backend

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:     /login
    defaults: { _controller: AgenciaActorsBackendBundle:Security:login }
 
login_check:
    path: /login_check
    
logout:
    path: /logout

